### ISSUE TITLE
LICENCE

### ISSUE THREAD

**Issue by jaronah** [machal/blanka-html#1]
Hi, what licence is blanka-html please? Can I use it for commercial use? I can't find any licence info.

**Comment by machal** [comment]
Thanks for the issue! I've just added MIT licence. Feel free to use it for commercial projects too.

https://github.com/machal/blanka-html/pull/2/commits/49083e732d3a571c63f518a1774bfed805430a51

**Comment by jaronah** [comment]
Thank you very much!

**Comment by jaronah** [comment]
I have one more question about the licence. I'm not sure how should I include licence in my source code the right way. According to what is written in the licence file - Should I copy all the text below and add it in blanka.css?

/* 
MIT License

Copyright (c) 2019 Martin Michálek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

**The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.**
*/


Or just include it this way?

/*
MIT License | Copyright (c) 2019 Martin Michálek | https://github.com/machal/blanka-html
*/

Thanks.

**Comment by machal** [comment]
Second one. :) As in Normalize.css for example: https://github.com/necolas/normalize.css/blob/master/normalize.css#L1

**Comment by jaronah** [comment]
Thank you :)
